# Ruumiobjektid ja ruumiandmed {#ruumiobjektid}


Selleks, et esitada GISis meid ümbritsevaid objekte ja nähtusi, peame valima sobiva kujutusviisi ja detailsusastme. Võime jagada objektid olemuslikult kahte rühma: diskreetsed ja pidevad. Diskreesed nähtused on konkreetselt piiritletavad 

Ruumiandmete põhitüübid on vektor- ja rasterandmed. Rasterandmed, mida kaardil kujutavad pikslid. Raster data is stored as a grid of values which are rendered on a map as pixels. 


**Ruumiobjektid** ongi mingi reaalmaailma (ka väljamõeldud või kujuteldava maailma) nähtuse **abstraktsed kujutised**, mis on seotud konkreetse asukoha või geograafilise alaga. Põhilised ruumiobjektide klassid on punkt, joon, polügoon.

Punkt on kõige elementaarsem ruumiobjekti tüüp ning on aluseks ka joontele ja polügoonidele. Punkti asukoha määravad ära kaks koordinaati (x ja y).

Joon koosneb mitmest punktist ega või iseendaga lõikuda. Joontena kujutatakse tüüpiliselt jõgesid

Polügoon on omakorda erinevate joonte kogum. Eristatakse polügoone, mis võivad teineteisega lõikuda, ja neid, mis ei või.



Ruumiandmed on andmed, mis osutavad mingile ruumiobjektile ning kirjeldavad tema asukohta, omadusi ja kuju.

dmed, mis otseselt või kaudselt osutavad konkreetsele asukohale või geograafilisele alale, sealhulgas andmekogudes hallatavad andmed, mis kirjeldavad ruumiobjektide asukohta, omadusi ja kuju geograafilises ruumis.  Ruumiandmekogum käesoleva seaduse tähenduses on ruumiandmete selgelt piiritletav kogum, sealhulgasandmekogu, mille koosseisus töödeldakse ruumiandmeid, või selle andmekogu osa.


Selleks, et lähemalt rääkida põhilistest ruumiobjektide tüüpidest, tuleb esmalt rääkida erinevatest andmemudelitest. 

Vektor

Raster



Vektormudelis punktid, jooned, polügoonid, multipolügoonid

Rastermudelis pikslid

Punktid, jooned, polügoonid.
Pikslid (raster, vektor)
Millisena saaksid kujutada enda andmeid?
Koordinaatsüsteem, projektsioon
Andmete struktureerimine 
